export const CONTRACTOR_TYPE_LABELS: Record<string, string> = {
  registered_nurse: 'Registered Nurse (RN)',
  licensed_practical_nurse: 'Licensed Practical Nurse (LPN)',
  certified_nursing_assistant: 'Certified Nursing Assistant (CNA)',
  nurse_practitioner: 'Nurse Practitioner (NP)',
  physician_assistant: 'Physician Assistant (PA)',
  medical_assistant: 'Medical Assistant (MA)',
  physical_therapist: 'Physical Therapist (PT)',
  occupational_therapist: 'Occupational Therapist (OT)',
  speech_language_pathologist: 'Speech-Language Pathologist (SLP)',
  respiratory_therapist: 'Respiratory Therapist (RT)',
  pharmacist: 'Pharmacist',
  radiology_technologist: 'Radiology Technologist',
  lab_technician: 'Lab Technician',
  surgical_technologist: 'Surgical Technologist',
  home_health_aide: 'Home Health Aide (HHA)',
  other: 'Other',
}

export const FACILITY_TYPE_LABELS: Record<string, string> = {
  hospital: 'Hospital',
  clinic: 'Clinic',
  nursing_home: 'Nursing Home',
  assisted_living: 'Assisted Living Facility',
  rehabilitation_center: 'Rehabilitation Center',
  home_health_agency: 'Home Health Agency',
  urgent_care: 'Urgent Care Center',
  long_term_care: 'Long-Term Care Facility',
  hospice: 'Hospice',
  outpatient_center: 'Outpatient Center',
  surgical_center: 'Surgical Center',
  mental_health_facility: 'Mental Health Facility',
  staffing_agency: 'Staffing Agency',
  other: 'Other',
}

export const CREDENTIAL_TYPE_LABELS: Record<string, string> = {
  license: 'Professional License',
  certification: 'Certification',
  degree: 'Degree',
  cpr_bls: 'CPR/BLS Certification',
  acls: 'ACLS Certification',
  pals: 'PALS Certification',
  nrp: 'NRP Certification',
  tncc: 'TNCC Certification',
  background_check: 'Background Check',
  drug_screen: 'Drug Screen',
  immunization: 'Immunization Record',
  tb_test: 'TB Test',
  fit_test: 'Fit Test',
  other: 'Other',
}

export const JOB_TYPE_LABELS: Record<string, string> = {
  per_diem: 'Per Diem',
  travel: 'Travel',
  contract: 'Contract',
  permanent: 'Permanent',
  temp_to_perm: 'Temp-to-Perm',
  local_contract: 'Local Contract',
}

export const SHIFT_TYPE_LABELS: Record<string, string> = {
  day: 'Day Shift',
  evening: 'Evening Shift',
  night: 'Night Shift',
  rotating: 'Rotating',
  flexible: 'Flexible',
  on_call: 'On Call',
  '8_hour': '8-Hour Shift',
  '10_hour': '10-Hour Shift',
  '12_hour': '12-Hour Shift',
}

export const US_STATES: { value: string; label: string }[] = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'DC', label: 'District of Columbia' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
]
