import type { QueueRow } from '../queue-client'
import type { ApplicantData } from './shared'

/** Sample data so the admin verification console renders in demo mode. */

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString()
const daysFromNow = (n: number) => new Date(Date.now() + n * 86_400_000).toISOString()

export const DEMO_APPLICANT_ID = 'demo-applicant-1'

export const DEMO_QUEUE: QueueRow[] = [
  {
    id: DEMO_APPLICANT_ID,
    name: 'Sarah Johnson',
    email: 'sarah.johnson@example.com',
    category: 'clinical',
    otherProfession: null,
    credentialBasis: null,
    status: 'pending_review',
    updatedAt: daysAgo(1),
    disclosuresYes: ['malpractice'],
    duplicateCount: 0,
    rescreenDue: false,
    lastExclusionCheckAt: null,
    insuranceDueAt: null,
  },
  {
    id: 'demo-applicant-2',
    name: 'Jordan Lee',
    email: 'jordan.lee@example.com',
    category: 'other',
    otherProfession: 'Doula',
    credentialBasis: 'certification',
    status: 'pending_review',
    updatedAt: daysAgo(2),
    disclosuresYes: [],
    duplicateCount: 1,
    rescreenDue: false,
    lastExclusionCheckAt: null,
    insuranceDueAt: null,
  },
  {
    id: 'demo-applicant-3',
    name: 'Maria Santos',
    email: 'maria.santos@example.com',
    category: 'clinical',
    otherProfession: null,
    credentialBasis: null,
    status: 'insurance_pending',
    updatedAt: daysAgo(10),
    disclosuresYes: [],
    duplicateCount: 0,
    rescreenDue: false,
    lastExclusionCheckAt: daysAgo(10),
    insuranceDueAt: daysFromNow(6),
  },
  {
    id: 'demo-applicant-4',
    name: 'Rachel Kim',
    email: 'rachel.kim@example.com',
    category: 'allied',
    otherProfession: null,
    credentialBasis: null,
    status: 'approved',
    updatedAt: daysAgo(45),
    disclosuresYes: [],
    duplicateCount: 0,
    rescreenDue: true,
    lastExclusionCheckAt: daysAgo(44),
    insuranceDueAt: null,
  },
  {
    id: 'demo-applicant-5',
    name: 'Alex Rivera',
    email: 'alex.rivera@example.com',
    category: 'consultant',
    otherProfession: null,
    credentialBasis: null,
    status: 'more_info_requested',
    updatedAt: daysAgo(3),
    disclosuresYes: [],
    duplicateCount: 0,
    rescreenDue: false,
    lastExclusionCheckAt: null,
    insuranceDueAt: null,
  },
]

export const DEMO_APPLICANT: ApplicantData = {
  profile: {
    id: DEMO_APPLICANT_ID,
    first_name: 'Sarah',
    last_name: 'Johnson',
    email: 'sarah.johnson@example.com',
    phone: '(555) 555-0142',
    contractor_type: 'rn',
    professional_category: 'clinical',
    other_profession: null,
    credential_basis: null,
    legal_name: 'Sarah M. Johnson',
    other_names: 'Sarah Miller',
    license_type: 'Registered Nurse (RN)',
    specialties: ['IV therapy'],
    state_license_number: 'RN 123456',
    license_states: ['CA', 'AZ'],
    license_issue_date: '2017-06-01',
    license_expiration_date: '2027-05-31',
    has_compact_license: false,
    telehealth_states: ['CA'],
    npi_number: '1234567893',
    years_of_experience: 8,
    certification_type: null,
    certifying_organization: null,
    consulting_background: null,
    client_types: [],
    website_url: null,
    primary_background: null,
    teaching_topics: null,
    ceu_accreditation: null,
    offers_high_risk_services: true,
    self_disclosures: {
      license_action: { answer: false, details: null },
      exclusion: { answer: false, details: null },
      conviction: { answer: false, details: null },
      malpractice: {
        answer: true,
        details: '2019 settlement, no admission of fault. Documentation available on request.',
      },
    },
    carries_liability_insurance: true,
    attested_accurate_at: daysAgo(1),
    authorized_checks_at: daysAgo(1),
    verification_status: 'pending_review',
    verification_notes: null,
    verification_reviewed_at: null,
    approved_at: null,
    insurance_due_at: null,
    insured_verified_at: null,
    compliance_hold_reason: null,
    last_exclusion_check_at: null,
    admin_checklist: {
      oig_leie: { done: true, by: 'demo', at: daysAgo(0), note: 'No match' },
    },
    contractor_agreement_accepted_at: null,
    city: 'Los Angeles',
    state: 'CA',
    created_at: daysAgo(2),
    onboarding_completed_at: daysAgo(1),
  },
  credentials: [
    {
      id: 'demo-cred-1',
      credential_type: 'license',
      name: 'License or certification photo',
      issuing_authority: null,
      license_number: null,
      issued_date: null,
      expiration_date: null,
      coverage_amount: null,
      status: 'pending_review',
      has_document: false,
      document_filename: 'rn-license.jpg',
      verified_at: null,
      created_at: daysAgo(1),
    },
    {
      id: 'demo-cred-2',
      credential_type: 'government_id',
      name: 'Government photo ID',
      issuing_authority: null,
      license_number: null,
      issued_date: null,
      expiration_date: null,
      coverage_amount: null,
      status: 'pending_review',
      has_document: false,
      document_filename: 'drivers-license.jpg',
      verified_at: null,
      created_at: daysAgo(1),
    },
    {
      id: 'demo-cred-3',
      credential_type: 'malpractice_insurance',
      name: 'Malpractice insurance certificate',
      issuing_authority: 'NSO',
      license_number: 'POL-998877',
      issued_date: null,
      expiration_date: '2027-01-15',
      coverage_amount: '$1M / $3M',
      status: 'pending_review',
      has_document: false,
      document_filename: 'coi.pdf',
      verified_at: null,
      created_at: daysAgo(1),
    },
  ],
  evidence: [
    {
      id: 'demo-ev-1',
      check_key: 'oig_leie',
      note: null,
      created_by: 'demo',
      created_at: daysAgo(0),
      filename: 'oig-search.png',
    },
  ],
  duplicates: [],
  checks: [],
  offerings: [
    {
      id: 'demo-off-1',
      title: 'In-home IV hydration',
      status: 'draft',
      format: 'home_visit',
      requires_malpractice: true,
    },
  ],
  adminNames: { demo: 'admin@sanus.demo' },
}
