// This file will be auto-generated by: npx supabase gen types typescript --local > src/types/database.ts
// For now, we provide a minimal placeholder so imports don't break.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

type AnyTable = {
  Row: Record<string, Json>
  Insert: Record<string, Json>
  Update: Record<string, Json>
  Relationships: unknown[]
}

export type Database = {
  public: {
    Tables: Record<string, AnyTable>
    Views: Record<string, AnyTable>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
    CompositeTypes: Record<string, unknown>
  }
}
