// This file will be auto-generated by: npx supabase gen types typescript --local > src/types/database.ts
// For now, we provide a minimal placeholder so imports don't break.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyTable = {
  Row: Record<string, any>
  Insert: Record<string, any>
  Update: Record<string, any>
  Relationships: any[]
}

export type Database = {
  public: {
    Tables: Record<string, AnyTable>
    Views: Record<string, AnyTable>
    Functions: Record<string, any>
    Enums: Record<string, any>
    CompositeTypes: Record<string, any>
  }
}
