// Demo user profiles
export const DEMO_CONTRACTOR = {
  id: 'demo-contractor-1',
  email: 'sarah.johnson@demo.com',
  role: 'contractor' as const,
  avatar_url: null,
  first_name: 'Sarah',
  last_name: 'Johnson',
  contractor_type: 'rn',
  specialties: ['ICU', 'Emergency', 'Cardiac Care', 'Trauma'],
  headline: 'Experienced ICU Nurse | 8+ Years Critical Care',
  bio: 'Dedicated registered nurse with extensive experience in intensive care units. Specialized in cardiac monitoring, ventilator management, and critical care protocols. Available for travel and per-diem assignments.',
  years_of_experience: 8,
  hourly_rate_min: 55,
  hourly_rate_max: 85,
  npi_number: '1234567890',
  state_license_number: 'RN-123456',
  license_state: 'CA',
  city: 'Los Angeles',
  state: 'CA',
  zip_code: '90001',
  willing_to_travel: true,
  travel_radius_miles: 100,
  is_available: true,
  profile_completion_pct: 85,
  total_jobs_completed: 24,
  average_rating: 4.9,
  total_reviews: 18,
  stripe_connect_id: null,
  stripe_connect_onboarded: false,
}

export const DEMO_FACILITY = {
  id: 'demo-facility-1',
  email: 'admin@northlinemedical.com',
  role: 'facility' as const,
  avatar_url: null,
  facility_name: 'Northline Medical Center',
  facility_type: 'hospital',
  description:
    'A 320-bed acute care hospital serving the greater Los Angeles area. We provide comprehensive medical services including emergency care, surgery, and specialized treatments.',
  website: 'https://northlinemedical.com',
  address_line1: '1200 Health Boulevard',
  city: 'Los Angeles',
  state: 'CA',
  zip_code: '90012',
  phone: '(213) 555-0100',
  contact_name: 'Dr. Michael Chen',
  contact_title: 'Chief Medical Officer',
  contact_email: 'mchen@northlinemedical.com',
  average_rating: 4.7,
  total_reviews: 42,
  is_verified: true,
  total_jobs_posted: 15,
}

// Demo credentials (for contractor)
export const DEMO_CREDENTIALS = [
  {
    id: 'cred-1',
    contractor_id: 'demo-contractor-1',
    credential_type: 'license',
    name: 'California RN License',
    issuing_authority: 'California Board of Registered Nursing',
    license_number: 'RN-123456',
    issued_date: '2018-06-15',
    expiration_date: '2026-06-15',
    status: 'verified',
    document_url: null,
    document_filename: 'rn_license.pdf',
    auto_verified: false,
    verified_at: '2024-01-10T00:00:00Z',
  },
  {
    id: 'cred-2',
    contractor_id: 'demo-contractor-1',
    credential_type: 'cpr_bls',
    name: 'BLS Certification',
    issuing_authority: 'American Heart Association',
    license_number: 'BLS-789012',
    issued_date: '2024-01-20',
    expiration_date: '2026-01-20',
    status: 'verified',
    document_url: null,
    document_filename: 'bls_cert.pdf',
    auto_verified: false,
    verified_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'cred-3',
    contractor_id: 'demo-contractor-1',
    credential_type: 'acls',
    name: 'ACLS Certification',
    issuing_authority: 'American Heart Association',
    license_number: 'ACLS-345678',
    issued_date: '2024-03-10',
    expiration_date: '2026-03-10',
    status: 'verified',
    document_url: null,
    document_filename: 'acls_cert.pdf',
    auto_verified: false,
    verified_at: '2024-03-15T00:00:00Z',
  },
  {
    id: 'cred-4',
    contractor_id: 'demo-contractor-1',
    credential_type: 'background_check',
    name: 'Background Check',
    issuing_authority: 'Checkr',
    license_number: null,
    issued_date: '2024-06-01',
    expiration_date: '2025-06-01',
    status: 'expiring_soon',
    document_url: null,
    document_filename: 'bg_check.pdf',
    auto_verified: true,
    verified_at: '2024-06-05T00:00:00Z',
  },
  {
    id: 'cred-5',
    contractor_id: 'demo-contractor-1',
    credential_type: 'immunization',
    name: 'Immunization Records',
    issuing_authority: null,
    license_number: null,
    issued_date: null,
    expiration_date: null,
    status: 'pending_review',
    document_url: null,
    document_filename: 'immunizations.pdf',
    auto_verified: false,
    verified_at: null,
  },
]

// Demo jobs (realistic healthcare positions)
export const DEMO_JOBS = [
  {
    id: 'job-1',
    facility_id: 'demo-facility-1',
    title: 'ICU Registered Nurse — Night Shift',
    description:
      'Seeking an experienced ICU RN for night shift coverage at our Level II trauma center. Must have minimum 3 years ICU experience and current ACLS certification. This is a 13-week travel contract with competitive pay and housing stipend.',
    contractor_type: 'rn',
    specialties_required: ['ICU', 'Critical Care'],
    job_type: 'travel',
    shift_type: 'night',
    status: 'open',
    city: 'Los Angeles',
    state: 'CA',
    zip_code: '90012',
    is_remote: false,
    pay_rate_min: 75,
    pay_rate_max: 92,
    pay_rate_type: 'hourly',
    overtime_rate: 112,
    travel_reimbursement: true,
    housing_provided: true,
    start_date: '2026-06-15',
    end_date: '2026-09-14',
    shifts_per_week: 3,
    hours_per_shift: 12,
    years_experience_min: 3,
    required_credentials: ['RN License', 'BLS', 'ACLS'],
    additional_requirements:
      'Must be comfortable with ventilator management and hemodynamic monitoring.',
    total_applicants: 12,
    positions_available: 2,
    positions_filled: 0,
    urgency: 'high',
    published_at: '2026-05-20T10:00:00Z',
    created_at: '2026-05-20T10:00:00Z',
    facility: {
      facility_name: 'Northline Medical Center',
      city: 'Los Angeles',
      state: 'CA',
      average_rating: 4.7,
    },
  },
  {
    id: 'job-2',
    facility_id: 'demo-facility-2',
    title: 'Emergency Room Nurse Practitioner',
    description:
      'Fast-paced ER seeking a board-certified nurse practitioner. Join our team of providers managing a 60,000+ annual visit emergency department. Full autonomy with physician backup available.',
    contractor_type: 'np',
    specialties_required: ['Emergency Medicine'],
    job_type: 'contract',
    shift_type: 'rotating',
    status: 'open',
    city: 'Phoenix',
    state: 'AZ',
    zip_code: '85001',
    is_remote: false,
    pay_rate_min: 95,
    pay_rate_max: 115,
    pay_rate_type: 'hourly',
    overtime_rate: null,
    travel_reimbursement: false,
    housing_provided: false,
    start_date: '2026-07-01',
    end_date: '2026-12-31',
    shifts_per_week: 4,
    hours_per_shift: 10,
    years_experience_min: 2,
    required_credentials: ['NP License', 'BLS', 'ACLS'],
    additional_requirements: null,
    total_applicants: 8,
    positions_available: 1,
    positions_filled: 0,
    urgency: 'normal',
    published_at: '2026-05-18T14:00:00Z',
    created_at: '2026-05-18T14:00:00Z',
    facility: {
      facility_name: 'Valley Regional Medical Center',
      city: 'Phoenix',
      state: 'AZ',
      average_rating: 4.5,
    },
  },
  {
    id: 'job-3',
    facility_id: 'demo-facility-3',
    title: 'Certified Nursing Assistant — Day Shift',
    description:
      'Greenway Skilled Nursing is seeking compassionate CNAs for day shift positions. Provide direct patient care including bathing, feeding, vital signs, and mobility assistance to our elderly residents.',
    contractor_type: 'cna',
    specialties_required: ['Long-term Care', 'Geriatrics'],
    job_type: 'per_diem',
    shift_type: 'day',
    status: 'open',
    city: 'Austin',
    state: 'TX',
    zip_code: '78701',
    is_remote: false,
    pay_rate_min: 22,
    pay_rate_max: 28,
    pay_rate_type: 'hourly',
    overtime_rate: 33,
    travel_reimbursement: false,
    housing_provided: false,
    start_date: '2026-05-28',
    end_date: null,
    shifts_per_week: null,
    hours_per_shift: 8,
    years_experience_min: 1,
    required_credentials: ['CNA Certification', 'BLS'],
    additional_requirements: 'Must pass background check and drug screen.',
    total_applicants: 23,
    positions_available: 5,
    positions_filled: 2,
    urgency: 'critical',
    published_at: '2026-05-15T08:00:00Z',
    created_at: '2026-05-15T08:00:00Z',
    facility: {
      facility_name: 'Greenway Skilled Nursing',
      city: 'Austin',
      state: 'TX',
      average_rating: 4.3,
    },
  },
  {
    id: 'job-4',
    facility_id: 'demo-facility-4',
    title: 'Physical Therapist — Outpatient Ortho',
    description:
      'Looking for a skilled physical therapist to join our outpatient orthopedic clinic. Treat post-surgical patients, sports injuries, and chronic pain cases. Modern equipment and supportive team environment.',
    contractor_type: 'pt',
    specialties_required: ['Orthopedics', 'Sports Medicine'],
    job_type: 'contract',
    shift_type: 'day',
    status: 'open',
    city: 'Denver',
    state: 'CO',
    zip_code: '80202',
    is_remote: false,
    pay_rate_min: 55,
    pay_rate_max: 70,
    pay_rate_type: 'hourly',
    overtime_rate: null,
    travel_reimbursement: false,
    housing_provided: false,
    start_date: '2026-06-01',
    end_date: '2026-11-30',
    shifts_per_week: 5,
    hours_per_shift: 8,
    years_experience_min: 2,
    required_credentials: ['PT License', 'BLS'],
    additional_requirements: null,
    total_applicants: 6,
    positions_available: 1,
    positions_filled: 0,
    urgency: 'normal',
    published_at: '2026-05-19T09:00:00Z',
    created_at: '2026-05-19T09:00:00Z',
    facility: {
      facility_name: 'Peak Performance Rehab Center',
      city: 'Denver',
      state: 'CO',
      average_rating: 4.8,
    },
  },
  {
    id: 'job-5',
    facility_id: 'demo-facility-1',
    title: 'Respiratory Therapist — Travel Assignment',
    description:
      'Travel respiratory therapist needed for a 13-week assignment. Manage ventilators, perform arterial blood gases, and administer treatments. Housing stipend and travel reimbursement included.',
    contractor_type: 'rt',
    specialties_required: ['Critical Care', 'Pulmonary'],
    job_type: 'travel',
    shift_type: 'night',
    status: 'open',
    city: 'Los Angeles',
    state: 'CA',
    zip_code: '90012',
    is_remote: false,
    pay_rate_min: 60,
    pay_rate_max: 78,
    pay_rate_type: 'hourly',
    overtime_rate: 95,
    travel_reimbursement: true,
    housing_provided: true,
    start_date: '2026-06-22',
    end_date: '2026-09-21',
    shifts_per_week: 3,
    hours_per_shift: 12,
    years_experience_min: 2,
    required_credentials: ['RT License', 'BLS', 'ACLS'],
    additional_requirements: null,
    total_applicants: 4,
    positions_available: 1,
    positions_filled: 0,
    urgency: 'high',
    published_at: '2026-05-21T11:00:00Z',
    created_at: '2026-05-21T11:00:00Z',
    facility: {
      facility_name: 'Northline Medical Center',
      city: 'Los Angeles',
      state: 'CA',
      average_rating: 4.7,
    },
  },
  {
    id: 'job-6',
    facility_id: 'demo-facility-5',
    title: 'Locum Tenens Physician — Family Medicine',
    description:
      'Seeking a board-certified family medicine physician for locum tenens coverage at our rural clinic. Provide primary care services for a diverse patient population. Malpractice coverage provided.',
    contractor_type: 'md',
    specialties_required: ['Family Medicine', 'Primary Care'],
    job_type: 'locum_tenens',
    shift_type: 'day',
    status: 'open',
    city: 'Boise',
    state: 'ID',
    zip_code: '83702',
    is_remote: false,
    pay_rate_min: 150,
    pay_rate_max: 200,
    pay_rate_type: 'hourly',
    overtime_rate: null,
    travel_reimbursement: true,
    housing_provided: true,
    start_date: '2026-07-15',
    end_date: '2026-10-15',
    shifts_per_week: 5,
    hours_per_shift: 8,
    years_experience_min: 5,
    required_credentials: ['Medical License', 'DEA', 'BLS'],
    additional_requirements:
      'Board certification in Family Medicine required.',
    total_applicants: 3,
    positions_available: 1,
    positions_filled: 0,
    urgency: 'normal',
    published_at: '2026-05-17T12:00:00Z',
    created_at: '2026-05-17T12:00:00Z',
    facility: {
      facility_name: 'Mountain View Community Clinic',
      city: 'Boise',
      state: 'ID',
      average_rating: 4.6,
    },
  },
]

// Demo contracts
export const DEMO_CONTRACTS = [
  {
    id: 'contract-1',
    job_id: 'job-1',
    contractor_id: 'demo-contractor-1',
    facility_id: 'demo-facility-1',
    status: 'active',
    title: 'ICU RN Night Shift — 13 Week Contract',
    description: 'Night shift ICU coverage',
    agreed_rate: 82,
    rate_type: 'hourly',
    overtime_rate: 112,
    estimated_hours: 468,
    total_value: 38376,
    platform_fee_pct: 10,
    start_date: '2026-04-01',
    end_date: '2026-06-30',
    shift_type: 'night',
    shifts_per_week: 3,
    hours_per_shift: 12,
    contractor_signed_at: '2026-03-25T00:00:00Z',
    facility_signed_at: '2026-03-25T00:00:00Z',
    created_at: '2026-03-20T00:00:00Z',
    facility: { facility_name: 'Northline Medical Center' },
    contractor: {
      first_name: 'Sarah',
      last_name: 'Johnson',
      contractor_type: 'rn',
    },
  },
  {
    id: 'contract-2',
    job_id: null,
    contractor_id: 'demo-contractor-1',
    facility_id: 'demo-facility-3',
    status: 'completed',
    title: 'Per Diem CNA Coverage — March',
    description: 'Day shift CNA coverage',
    agreed_rate: 45,
    rate_type: 'hourly',
    overtime_rate: null,
    estimated_hours: 80,
    total_value: 3600,
    platform_fee_pct: 10,
    start_date: '2026-03-01',
    end_date: '2026-03-31',
    shift_type: 'day',
    shifts_per_week: 2,
    hours_per_shift: 10,
    contractor_signed_at: '2026-02-28T00:00:00Z',
    facility_signed_at: '2026-02-28T00:00:00Z',
    created_at: '2026-02-25T00:00:00Z',
    facility: { facility_name: 'Greenway Skilled Nursing' },
    contractor: {
      first_name: 'Sarah',
      last_name: 'Johnson',
      contractor_type: 'rn',
    },
  },
]

// Demo timesheets
export const DEMO_TIMESHEETS = [
  {
    id: 'ts-1',
    contract_id: 'contract-1',
    contractor_id: 'demo-contractor-1',
    facility_id: 'demo-facility-1',
    status: 'approved',
    shift_date: '2026-05-20',
    clock_in: '2026-05-20T19:00:00Z',
    clock_out: '2026-05-21T07:00:00Z',
    break_minutes: 30,
    total_hours: 11.5,
    overtime_hours: 0,
    notes: null,
    submitted_at: '2026-05-21T08:00:00Z',
    approved_at: '2026-05-21T14:00:00Z',
  },
  {
    id: 'ts-2',
    contract_id: 'contract-1',
    contractor_id: 'demo-contractor-1',
    facility_id: 'demo-facility-1',
    status: 'approved',
    shift_date: '2026-05-22',
    clock_in: '2026-05-22T19:00:00Z',
    clock_out: '2026-05-23T07:00:00Z',
    break_minutes: 30,
    total_hours: 11.5,
    overtime_hours: 0,
    notes: null,
    submitted_at: '2026-05-23T08:00:00Z',
    approved_at: '2026-05-23T12:00:00Z',
  },
  {
    id: 'ts-3',
    contract_id: 'contract-1',
    contractor_id: 'demo-contractor-1',
    facility_id: 'demo-facility-1',
    status: 'submitted',
    shift_date: '2026-05-23',
    clock_in: '2026-05-23T19:00:00Z',
    clock_out: '2026-05-24T07:00:00Z',
    break_minutes: 30,
    total_hours: 11.5,
    overtime_hours: 0,
    notes: 'Handled 2 new admissions',
    submitted_at: '2026-05-24T08:00:00Z',
    approved_at: null,
  },
]

// Demo payments
export const DEMO_PAYMENTS = [
  {
    id: 'pay-1',
    contract_id: 'contract-1',
    payer_id: 'demo-facility-1',
    payee_id: 'demo-contractor-1',
    status: 'released',
    gross_amount: 943,
    platform_fee: 94.3,
    net_amount: 848.7,
    created_at: '2026-05-21T15:00:00Z',
    invoice_number: 'SAN-INV-10001',
    contracts: { title: 'ICU RN Night Shift — 13 Week Contract' },
  },
  {
    id: 'pay-2',
    contract_id: 'contract-1',
    payer_id: 'demo-facility-1',
    payee_id: 'demo-contractor-1',
    status: 'released',
    gross_amount: 943,
    platform_fee: 94.3,
    net_amount: 848.7,
    created_at: '2026-05-23T13:00:00Z',
    invoice_number: 'SAN-INV-10002',
    contracts: { title: 'ICU RN Night Shift — 13 Week Contract' },
  },
  {
    id: 'pay-3',
    contract_id: 'contract-1',
    payer_id: 'demo-facility-1',
    payee_id: 'demo-contractor-1',
    status: 'in_escrow',
    gross_amount: 943,
    platform_fee: 94.3,
    net_amount: 848.7,
    created_at: '2026-05-24T09:00:00Z',
    invoice_number: 'SAN-INV-10003',
    contracts: { title: 'ICU RN Night Shift — 13 Week Contract' },
  },
]

// Demo messages/conversations
export const DEMO_CONVERSATIONS = [
  {
    id: 'conv-1',
    participant_1: 'demo-contractor-1',
    participant_2: 'demo-facility-1',
    last_message_at: '2026-05-23T16:30:00Z',
    last_message_preview:
      'Sounds good! I will see you Monday night for the shift.',
    other_user: {
      name: 'Dr. Michael Chen',
      role: 'facility',
      avatar_url: null,
      email: 'mchen@northlinemedical.com',
    },
    unread_count: 0,
  },
  {
    id: 'conv-2',
    participant_1: 'demo-contractor-1',
    participant_2: 'demo-facility-3',
    last_message_at: '2026-05-22T10:15:00Z',
    last_message_preview:
      'Thank you for completing the assignment. We have submitted your final payment.',
    other_user: {
      name: 'Karen Williams',
      role: 'facility',
      avatar_url: null,
      email: 'kwilliams@greenway.com',
    },
    unread_count: 1,
  },
]

export const DEMO_MESSAGES = [
  {
    id: 'msg-1',
    conversation_id: 'conv-1',
    sender_id: 'demo-facility-1',
    content:
      'Hi Sarah, we have an opening for ICU night shift starting next Monday. Are you available?',
    is_read: true,
    created_at: '2026-05-23T14:00:00Z',
  },
  {
    id: 'msg-2',
    conversation_id: 'conv-1',
    sender_id: 'demo-contractor-1',
    content:
      'Hi Dr. Chen! Yes, I am available. What are the shift details?',
    is_read: true,
    created_at: '2026-05-23T14:30:00Z',
  },
  {
    id: 'msg-3',
    conversation_id: 'conv-1',
    sender_id: 'demo-facility-1',
    content:
      'It is 7pm to 7am, 3 nights a week. We are offering $82/hr with $112 overtime. Housing stipend included.',
    is_read: true,
    created_at: '2026-05-23T15:00:00Z',
  },
  {
    id: 'msg-4',
    conversation_id: 'conv-1',
    sender_id: 'demo-contractor-1',
    content:
      'That works perfectly for me. I will accept the contract.',
    is_read: true,
    created_at: '2026-05-23T15:45:00Z',
  },
  {
    id: 'msg-5',
    conversation_id: 'conv-1',
    sender_id: 'demo-facility-1',
    content:
      'Great! I have sent the contract for your review. Welcome aboard!',
    is_read: true,
    created_at: '2026-05-23T16:00:00Z',
  },
  {
    id: 'msg-6',
    conversation_id: 'conv-1',
    sender_id: 'demo-contractor-1',
    content:
      'Sounds good! I will see you Monday night for the shift.',
    is_read: true,
    created_at: '2026-05-23T16:30:00Z',
  },
]

// Demo notifications
export const DEMO_NOTIFICATIONS = [
  {
    id: 'notif-1',
    user_id: 'demo-contractor-1',
    type: 'payment_received',
    title: 'Payment Received',
    body: 'You received $848.70 for your ICU Night Shift timesheet.',
    is_read: false,
    created_at: '2026-05-23T13:00:00Z',
    data: { payment_id: 'pay-2' },
  },
  {
    id: 'notif-2',
    user_id: 'demo-contractor-1',
    type: 'timesheet_approved',
    title: 'Timesheet Approved',
    body: 'Your timesheet for May 22 has been approved by Northline Medical Center.',
    is_read: false,
    created_at: '2026-05-23T12:00:00Z',
    data: { timesheet_id: 'ts-2' },
  },
  {
    id: 'notif-3',
    user_id: 'demo-contractor-1',
    type: 'job_match',
    title: 'New Job Match',
    body: 'A new ICU position in Los Angeles matches your profile.',
    is_read: true,
    created_at: '2026-05-21T11:00:00Z',
    data: { job_id: 'job-1' },
  },
  {
    id: 'notif-4',
    user_id: 'demo-contractor-1',
    type: 'credential_expiring',
    title: 'Credential Expiring Soon',
    body: 'Your Background Check expires on June 1, 2025. Please renew.',
    is_read: true,
    created_at: '2026-05-20T08:00:00Z',
    data: { credential_id: 'cred-4' },
  },
  {
    id: 'notif-5',
    user_id: 'demo-contractor-1',
    type: 'new_message',
    title: 'New Message',
    body: 'Dr. Michael Chen sent you a message about the ICU position.',
    is_read: true,
    created_at: '2026-05-23T14:00:00Z',
    data: { conversation_id: 'conv-1' },
  },
]

// Demo reviews
export const DEMO_REVIEWS = [
  {
    id: 'rev-1',
    contract_id: 'contract-2',
    reviewer_id: 'demo-facility-3',
    reviewee_id: 'demo-contractor-1',
    rating: 5,
    title: 'Excellent clinician',
    content:
      'Sarah was outstanding during her assignment. Professional, punctual, and patients loved her. Would definitely hire again.',
    professionalism_rating: 5,
    communication_rating: 5,
    skill_rating: 5,
    punctuality_rating: 5,
    created_at: '2026-04-05T00:00:00Z',
    reviewer: { first_name: 'Karen', last_name: 'Williams' },
  },
  {
    id: 'rev-2',
    contract_id: 'contract-2',
    reviewer_id: 'demo-facility-1',
    reviewee_id: 'demo-contractor-1',
    rating: 5,
    title: 'Highly recommend',
    content:
      'Sarah adapted quickly to our ICU protocols and was a great addition to the team. Strong clinical skills.',
    professionalism_rating: 5,
    communication_rating: 4,
    skill_rating: 5,
    punctuality_rating: 5,
    created_at: '2026-03-20T00:00:00Z',
    reviewer: { first_name: 'Dr. Michael', last_name: 'Chen' },
  },
  {
    id: 'rev-3',
    contract_id: 'contract-2',
    reviewer_id: 'demo-facility-2',
    reviewee_id: 'demo-contractor-1',
    rating: 4,
    title: 'Solid performer',
    content:
      'Good work ethic and always on time. Would happily work with Sarah again on future assignments.',
    professionalism_rating: 4,
    communication_rating: 4,
    skill_rating: 4,
    punctuality_rating: 5,
    created_at: '2026-02-15T00:00:00Z',
    reviewer: { first_name: 'James', last_name: 'Rodriguez' },
  },
]

// Demo required credentials for RN
export const DEMO_REQUIRED_CREDENTIALS = [
  {
    id: 'req-1',
    contractor_type: 'rn',
    credential_type: 'license',
    name: 'State RN License',
    is_mandatory: true,
  },
  {
    id: 'req-2',
    contractor_type: 'rn',
    credential_type: 'cpr_bls',
    name: 'BLS Certification',
    is_mandatory: true,
  },
  {
    id: 'req-3',
    contractor_type: 'rn',
    credential_type: 'background_check',
    name: 'Background Check',
    is_mandatory: true,
  },
  {
    id: 'req-4',
    contractor_type: 'rn',
    credential_type: 'drug_screen',
    name: 'Drug Screen',
    is_mandatory: true,
  },
  {
    id: 'req-5',
    contractor_type: 'rn',
    credential_type: 'immunization',
    name: 'Immunization Records',
    is_mandatory: true,
  },
  {
    id: 'req-6',
    contractor_type: 'rn',
    credential_type: 'tb_test',
    name: 'TB Test',
    is_mandatory: true,
  },
]

// Demo availability slots
export const DEMO_AVAILABILITY = [
  {
    id: 'avail-1',
    contractor_id: 'demo-contractor-1',
    day_of_week: 0,
    start_time: '19:00',
    end_time: '07:00',
    is_recurring: true,
    is_blocked: false,
    notes: null,
    start_date: null,
    end_date: null,
  },
  {
    id: 'avail-2',
    contractor_id: 'demo-contractor-1',
    day_of_week: 2,
    start_time: '19:00',
    end_time: '07:00',
    is_recurring: true,
    is_blocked: false,
    notes: null,
    start_date: null,
    end_date: null,
  },
  {
    id: 'avail-3',
    contractor_id: 'demo-contractor-1',
    day_of_week: 4,
    start_time: '19:00',
    end_time: '07:00',
    is_recurring: true,
    is_blocked: false,
    notes: null,
    start_date: null,
    end_date: null,
  },
]

// Demo events
export const DEMO_EVENTS = [
  {
    id: 'event-1',
    title: 'IV Therapy Fundamentals for Home Health Nurses',
    type: 'webinar' as const,
    date: '2026-12-15T14:00:00Z',
    instructor: 'Dr. Sarah Mitchell',
    price: 0,
    memberPrice: 0,
    description:
      'Learn the essentials of IV therapy administration in a home health setting. This comprehensive webinar covers peripheral IV insertion techniques, common IV medications, infusion rate calculations, and complication management. Ideal for nurses transitioning to home health or those seeking to refresh their IV therapy skills.',
    registered: 42,
    duration: '2 hours',
    prerequisites: ['Active RN or LPN license', 'Basic pharmacology knowledge'],
    learningObjectives: [
      'Demonstrate proper peripheral IV insertion technique',
      'Calculate infusion rates for common IV medications',
      'Identify and manage common IV therapy complications',
      'Apply infection control principles specific to home health IV therapy',
      'Document IV therapy procedures per regulatory standards',
    ],
    agenda: [
      { time: '2:00 PM', topic: 'Introduction & IV Therapy Overview' },
      { time: '2:30 PM', topic: 'Peripheral IV Insertion Techniques' },
      { time: '3:00 PM', topic: 'Common Medications & Rate Calculations' },
      { time: '3:30 PM', topic: 'Complication Management & Q&A' },
    ],
    instructorBio:
      'Dr. Sarah Mitchell is a board-certified nurse practitioner with over 15 years of experience in home health and infusion therapy. She currently serves as the Director of Clinical Education at Pacific Home Health Services.',
  },
  {
    id: 'event-2',
    title: 'Post-Surgical Home Care: What Patients Need to Know',
    type: 'workshop' as const,
    date: '2027-01-08T10:00:00Z',
    instructor: 'Maria Santos, PT',
    price: 49,
    memberPrice: 29,
    description:
      'Comprehensive workshop on post-surgical home care best practices. Covers wound care, mobility assistance, pain management, medication administration, and patient education. Includes hands-on practice scenarios and case studies from real-world post-surgical home care situations.',
    registered: 28,
    duration: '4 hours',
    prerequisites: ['Healthcare professional license or certification', 'Basic patient care experience'],
    learningObjectives: [
      'Develop individualized post-surgical care plans',
      'Implement evidence-based wound care protocols',
      'Guide patients through safe mobility and exercise progressions',
      'Recognize signs of post-surgical complications requiring escalation',
      'Educate patients and caregivers on self-care techniques',
    ],
    agenda: [
      { time: '10:00 AM', topic: 'Post-Surgical Assessment Framework' },
      { time: '10:45 AM', topic: 'Wound Care & Infection Prevention' },
      { time: '11:30 AM', topic: 'Mobility & Exercise Progressions' },
      { time: '12:15 PM', topic: 'Case Studies & Hands-on Practice' },
    ],
    instructorBio:
      'Maria Santos is a licensed physical therapist specializing in post-surgical rehabilitation. With 12 years of experience, she has developed rehabilitation programs for major hospital systems across the country.',
  },
  {
    id: 'event-3',
    title: 'Nutrition for Chronic Disease Management',
    type: 'certification' as const,
    date: null,
    instructor: 'Lisa Chen, RD',
    price: 129,
    memberPrice: 99,
    description:
      'Self-paced certification course covering nutritional interventions for managing chronic diseases including diabetes, heart disease, kidney disease, and COPD. Earn a professional certificate upon completion. Includes video lectures, interactive quizzes, case studies, and a final assessment.',
    registered: 156,
    duration: 'Self-paced (approx. 12 hours)',
    prerequisites: ['Healthcare professional license or certification'],
    learningObjectives: [
      'Design nutrition plans for patients with Type 2 diabetes',
      'Apply heart-healthy dietary guidelines in care plans',
      'Manage nutritional needs for patients with chronic kidney disease',
      'Counsel patients on dietary modifications for COPD management',
      'Integrate nutritional assessments into routine patient care',
    ],
    agenda: [
      { time: 'Module 1', topic: 'Foundations of Medical Nutrition Therapy' },
      { time: 'Module 2', topic: 'Diabetes Nutrition Management' },
      { time: 'Module 3', topic: 'Cardiovascular & Renal Nutrition' },
      { time: 'Module 4', topic: 'Respiratory & Integrative Approaches' },
    ],
    instructorBio:
      'Lisa Chen is a registered dietitian with specializations in chronic disease management and clinical nutrition. She has published extensively on nutritional interventions and serves as a consultant for leading healthcare organizations.',
  },
  {
    id: 'event-4',
    title: 'Advanced Wound Care Techniques',
    type: 'live_class' as const,
    date: '2027-02-05T15:00:00Z',
    instructor: 'James Wilson, RN',
    price: 39,
    memberPrice: 19,
    description:
      'Hands-on wound care techniques for healthcare professionals. Covers advanced dressing selection, negative pressure wound therapy, debridement techniques, and documentation standards. This live interactive class includes real-time demonstrations and opportunities to ask questions.',
    registered: 35,
    duration: '3 hours',
    prerequisites: ['Active nursing license (RN, LPN, or equivalent)', 'Basic wound care experience'],
    learningObjectives: [
      'Select appropriate advanced dressings for various wound types',
      'Apply negative pressure wound therapy correctly',
      'Perform basic wound debridement techniques safely',
      'Document wound assessments using standardized measurement tools',
      'Develop wound care protocols for home health settings',
    ],
    agenda: [
      { time: '3:00 PM', topic: 'Wound Assessment & Classification' },
      { time: '3:45 PM', topic: 'Advanced Dressing Selection & Application' },
      { time: '4:30 PM', topic: 'NPWT & Debridement Demonstrations' },
      { time: '5:15 PM', topic: 'Documentation & Case Discussion' },
    ],
    instructorBio:
      'James Wilson is a certified wound care nurse (CWCN) with 10 years of experience in both hospital and home health wound management. He leads the wound care education program at a major metropolitan health system.',
  },
  {
    id: 'event-5',
    title: 'HIPAA Compliance for Independent Providers',
    type: 'webinar' as const,
    date: '2027-01-20T12:00:00Z',
    instructor: 'Sanus Legal Team',
    price: 0,
    memberPrice: 0,
    description:
      'Essential HIPAA compliance training tailored for independent healthcare providers and contractors. Learn about your obligations under HIPAA, common compliance pitfalls, documentation requirements, and best practices for protecting patient health information in home and community settings.',
    registered: 89,
    duration: '1.5 hours',
    prerequisites: [],
    learningObjectives: [
      'Understand HIPAA Privacy and Security Rule requirements for independent providers',
      'Identify common HIPAA violations in home health and telehealth settings',
      'Implement proper PHI handling and storage procedures',
      'Create a personal HIPAA compliance checklist',
      'Respond appropriately to potential data breaches',
    ],
    agenda: [
      { time: '12:00 PM', topic: 'HIPAA Overview for Independent Providers' },
      { time: '12:30 PM', topic: 'Common Violations & Risk Areas' },
      { time: '1:00 PM', topic: 'Best Practices & Compliance Checklist' },
      { time: '1:15 PM', topic: 'Q&A Session' },
    ],
    instructorBio:
      'The Sanus Legal Team comprises healthcare attorneys and compliance specialists dedicated to helping independent providers navigate the complex regulatory landscape of healthcare.',
  },
]

// Demo membership
export const DEMO_MEMBERSHIP = {
  currentPlan: 'basic',
  plans: [
    {
      id: 'basic',
      name: 'Basic',
      price: 0,
      interval: 'month',
      features: [
        'Browse jobs & facilities',
        'Access public events & webinars',
        'Basic profile listing',
        'Book up to 3 sessions/month',
      ],
    },
    {
      id: 'professional',
      name: 'Professional',
      price: 29,
      interval: 'month',
      popular: true,
      features: [
        'Everything in Basic',
        'Post your services on marketplace',
        'Priority search placement',
        'Superbill generation',
        'HIPAA-compliant messaging',
        'Unlimited bookings',
      ],
    },
    {
      id: 'enterprise',
      name: 'Enterprise',
      price: 79,
      interval: 'month',
      features: [
        'Everything in Professional',
        'Dedicated care coordinator',
        'Custom care plans',
        'White-glove support',
        'Early access to events',
        'Priority support',
      ],
    },
  ],
}

// Demo providers for public search page
export const DEMO_PROVIDERS = [
  { id: 'prov-1', first_name: 'Sarah', last_name: 'Johnson', credential: 'RN', contractor_type: 'rn', specialty: 'ICU & Critical Care', specialties: ['ICU', 'Emergency', 'Cardiac Care'], headline: 'Experienced ICU Nurse | 8+ Years', hourly_rate_min: 55, hourly_rate_max: 85, city: 'Los Angeles', state: 'CA', average_rating: 4.9, total_reviews: 127, is_available: true, session_types: ['in_person', 'virtual'], years_of_experience: 8 },
  { id: 'prov-2', first_name: 'Michael', last_name: 'Chen', credential: 'MD', contractor_type: 'md', specialty: 'Emergency Medicine', specialties: ['Emergency Medicine', 'Urgent Care'], headline: 'Board-Certified ER Physician', hourly_rate_min: 150, hourly_rate_max: 200, city: 'Phoenix', state: 'AZ', average_rating: 4.8, total_reviews: 89, is_available: true, session_types: ['in_person', 'virtual'], years_of_experience: 15 },
  { id: 'prov-3', first_name: 'Maria', last_name: 'Santos', credential: 'PT', contractor_type: 'pt', specialty: 'Orthopedic Rehab', specialties: ['Orthopedics', 'Sports Medicine'], headline: 'Licensed Physical Therapist', hourly_rate_min: 55, hourly_rate_max: 70, city: 'Denver', state: 'CO', average_rating: 4.8, total_reviews: 84, is_available: true, session_types: ['in_person'], years_of_experience: 6 },
  { id: 'prov-4', first_name: 'Karen', last_name: 'Williams', credential: 'CNA', contractor_type: 'cna', specialty: 'Long-term & Geriatric Care', specialties: ['Long-term Care', 'Geriatrics'], headline: 'Compassionate CNA | Elderly Care', hourly_rate_min: 22, hourly_rate_max: 38, city: 'Austin', state: 'TX', average_rating: 4.7, total_reviews: 63, is_available: true, session_types: ['in_person'], years_of_experience: 4 },
  { id: 'prov-5', first_name: 'James', last_name: 'Rodriguez', credential: 'RRT', contractor_type: 'rt', specialty: 'Respiratory Therapy', specialties: ['Critical Care', 'Pulmonary'], headline: 'Respiratory Therapist | Ventilator Specialist', hourly_rate_min: 50, hourly_rate_max: 72, city: 'Chicago', state: 'IL', average_rating: 4.8, total_reviews: 71, is_available: false, session_types: ['in_person'], years_of_experience: 7 },
  { id: 'prov-6', first_name: 'Lisa', last_name: 'Chen', credential: 'RD', contractor_type: 'other', specialty: 'Clinical Nutrition', specialties: ['Nutrition', 'Wellness', 'Chronic Disease'], headline: 'Registered Dietitian | Chronic Disease', hourly_rate_min: 40, hourly_rate_max: 65, city: 'San Francisco', state: 'CA', average_rating: 4.9, total_reviews: 95, is_available: true, session_types: ['virtual', 'in_person'], years_of_experience: 10 },
  { id: 'prov-7', first_name: 'David', last_name: 'Thompson', credential: 'RN', contractor_type: 'rn', specialty: 'Travel Nursing', specialties: ['ICU', 'Med-Surg', 'Telemetry'], headline: 'Travel RN | Available Nationwide', hourly_rate_min: 65, hourly_rate_max: 95, city: 'Dallas', state: 'TX', average_rating: 4.7, total_reviews: 52, is_available: true, session_types: ['in_person'], years_of_experience: 5 },
  { id: 'prov-8', first_name: 'Rachel', last_name: 'Kim', credential: 'LCSW', contractor_type: 'sw', specialty: 'Mental Health Counseling', specialties: ['Anxiety', 'Depression', 'Trauma'], headline: 'Licensed Clinical Social Worker', hourly_rate_min: 45, hourly_rate_max: 75, city: 'Seattle', state: 'WA', average_rating: 4.9, total_reviews: 108, is_available: true, session_types: ['virtual', 'in_person'], years_of_experience: 9 },
]

// Helper to check if we are in demo mode
export function isDemoMode(): boolean {
  return (
    !process.env.NEXT_PUBLIC_SUPABASE_URL ||
    !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
  )
}
